cluster:
  mkdir -p logs/$(date +"%Y_%m_%d") &&
  sbatch
    --partition={resources.partition}
    --gpus={resources.gpu}
    --cpus-per-task={threads}
    --mem={resources.mem_mb}
    --time={resources.time}
    --job-name={rule}
    --output=logs/$(date +"%Y_%m_%d")/%j-{rule}.out
    --parsable
default-resources:
  - partition=local
  - gpu=0
  - mem_mb=32000
  - time="0-10:00:00"
restart-times: 2
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
latency-wait: 60
jobs: 10
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: ilp
use-conda: True
cluster-cancel: scancel
cluster-status: .profiles/slurm-status.py
rerun-triggers:
  - mtime
  - params
  - input
  - code
#  - software-env
show-failed-logs: True